spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  datasource:
    # ImMemory
    url: jdbc:h2:mem:numb
    username: sa
    password:
  h2.console.enabled: true

  data.rest:
    basePath: /api
    returnBodyOnCreate: true
